modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="pastenbt"
version="1.2"
displayName="PasteNBT"
description="Paste structures seamlessly!"
authors="Hatsune Akiko"

[[dependencies.pastenbt]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pastenbt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
